on:
  push:

jobs:
  named-tag:
    name: Create Tag
    runs-on: ubuntu-latest


    #outputs:
    #  output1: ${{ steps.step1.outputs.test }}
    
    steps:

    - uses: actions/checkout@v3
    
    #- id: step1
    #  run: echo "test=hello" >> "$GITHUB_OUTPUT"
      
    - name: Create tag  
      uses: actions/github-script@v5
      env:
        TAG_ID: '0.24'
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: refs/tags/context.env.TAG_ID,
            sha: context.sha
          })
