on:
  push:

jobs:
  tag:
    name: Create Tag
    runs-on: ubuntu-latest
    steps:
    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/0.1',
            sha: context.sha
          })
