on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/.github/**'
      
jobs:
  named-tag:
    name: Create Tag
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: set env
        run: echo "TAG_ID=$(grep 'version' README.md | awk '{ print $NF }' | tr -d '`' )" >> $GITHUB_ENV
        
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          custom_tag: ${{ env.TAG_ID }}

 #     - name: Call promote workflow
 #       uses: ./.github/workflows/promote-tag.yaml
 #       with:
 #         tag: ${{ env.TAG_ID }}
