on:
  push:

jobs:
  named-tag:
    name: Create Tag
    runs-on: ubuntu-latest


    #outputs:
    #  output1: ${{ steps.step1.outputs.test }}
    
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          custom_tag: 0.2.0
