on:
  workflow_dispatch:
    inputs:
      target_service:
        description: 'Input a service name (e.g., demo-app)'
        required: true
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="tchnmf" 
          repo_name="gitops"  
          event_type="trigger-workflow" 
          service=${{ github.event.inputs.target_service }}"
          version="${{ github.event.inputs.target_version }}"


            curl \
              -X POST \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
                  https://api.github.com/repos/tchnmf/gitops/actions/workflows/repository_dispatch/dispatches \
                  -d '{"ref":"refs/heads/master"}'

