on:
  workflow_dispatch:
    inputs:
      target_service:
        description: 'Input a service name (e.g., demo-app)'
        required: true
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="tchnmf" 
          repo_name="gitops"  
          event_type="test-result" 
          service=${{ github.event.inputs.target_service }}"
          version="${{ github.event.inputs.target_version }}"
          


      
      - name: call the other repo   
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          EVENT: test_result
          ORG: tchnmf
          REPO: gitops
        run: |
          curl -d "{\"event_type\": \"${EVENT}\"}" -H "Content-Type: application/json" -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/${ORG}/${REPO}/dispatches"
