on: push

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: call the other repo   
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          EVENT: test_result
          ORG: tchnmf
          REPO: gitops
          #Payload: '{"Name": "${env.BRANCH_NAME}" }'

        run: |
          #curl -d "{\"event_type\": \"${EVENT}\"}" -H "Content-Type: application/json" -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/${ORG}/${REPO}/dispatches"
          curl -d "{\"event_type\":\"test_result\",\"client_payload\":{\"passed\":false,\"message\":\"i-am-robot\"}}" -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/${ORG}/${REPO}/dispatches"
